-- Script para inserir funcionários no banco de dados
INSERT INTO employees (id, name, role, createdAt, updatedAt) VALUES 
(UUID(), 'Adryan Gabriel Alves', '', NOW(), NOW()),
(UUID(), 'Alexandre Francisco Souza Da Silva', '', NOW(), NOW()),
(UUID(), 'Alexandre Vinicius Santos', '', NOW(), NOW()),
(UUID(), 'Alexandro Souza Dos Santos', '', NOW(), NOW()),
(UUID(), 'Algary Feitosa Cavalcante', '', NOW(), NOW()),
(UUID(), 'Alison Valbert', '', NOW(), NOW()),
(UUID(), 'Amós Silvestre Dos Santos', '', NOW(), NOW()),
(UUID(), 'André Neres Santos', '', NOW(), NOW()),
(UUID(), 'Antônio Dizio Da Silva', '', NOW(), NOW()),
(UUID(), 'Antonio Marcos Alves De Souza', '', NOW(), NOW()),
(UUID(), 'Carlos Alberto Dos Santos', '', NOW(), NOW()),
(UUID(), 'Clebisson Dos Santos', '', NOW(), NOW()),
(UUID(), 'Cleisson Cardoso Dantas', '', NOW(), NOW()),
(UUID(), 'Cleverton De Andrade Santos', '', NOW(), NOW()),
(UUID(), 'David Lune Conceição', '', NOW(), NOW()),
(UUID(), 'Edidelson Santos', '', NOW(), NOW()),
(UUID(), 'Eraldo Pereira Santos', '', NOW(), NOW()),
(UUID(), 'Erivaldo Batista Santos Junior', '', NOW(), NOW()),
(UUID(), 'Esdras Phillip', '', NOW(), NOW()),
(UUID(), 'Everton Mendes Soares', '', NOW(), NOW()),
(UUID(), 'Francisco Cicero Da Silva', '', NOW(), NOW()),
(UUID(), 'Gabriel Dos Santos Costa', '', NOW(), NOW()),
(UUID(), 'Gabriel Santana Dos Santos', '', NOW(), NOW()),
(UUID(), 'Gabriel Santana Nogueira', '', NOW(), NOW()),
(UUID(), 'Helyel Santana Silva', '', NOW(), NOW()),
(UUID(), 'Humberto Rodrigues Dos Santos Neto', '', NOW(), NOW()),
(UUID(), 'Ivanilson Menezes Batista', '', NOW(), NOW()),
(UUID(), 'Izaias Da Paz Santos', '', NOW(), NOW()),
(UUID(), 'Jeizon Nunes Santos', '', NOW(), NOW()),
(UUID(), 'João Pedro Da Silva Santos', '', NOW(), NOW()),
(UUID(), 'Joelisson Dos Santos', '', NOW(), NOW()),
(UUID(), 'Jose Alisson De Lima Morais', '', NOW(), NOW()),
(UUID(), 'José Vanderley Francisco', '', NOW(), NOW()),
(UUID(), 'Josivan Da Silva Lima', '', NOW(), NOW()),
(UUID(), 'Luiz Carlos Maia Santos', '', NOW(), NOW()),
(UUID(), 'Magno Dos Santos', '', NOW(), NOW()),
(UUID(), 'Manoel Messias Dos Santos', '', NOW(), NOW()),
(UUID(), 'Marcelo Santos Santana', '', NOW(), NOW()),
(UUID(), 'Marcus Vinicius Gomes De Azevedo', '', NOW(), NOW()),
(UUID(), 'Mateus Souza Da Hora', '', NOW(), NOW()),
(UUID(), 'Matheus Santos Gomes', '', NOW(), NOW()),
(UUID(), 'Michael Alysson Jheckson Santos Silva', '', NOW(), NOW()),
(UUID(), 'Nathan Nascimento Santos', '', NOW(), NOW()),
(UUID(), 'Rafael Santos Bispo', '', NOW(), NOW()),
(UUID(), 'Robson Santos Da Silva', '', NOW(), NOW()),
(UUID(), 'Shairwandler Santos Santana', '', NOW(), NOW()),
(UUID(), 'Thiago Freire De Campos', '', NOW(), NOW()),
(UUID(), 'Walisson Tavares Dos Santos', '', NOW(), NOW()),
(UUID(), 'Welber Guilherme Dos Santos', '', NOW(), NOW()),
(UUID(), 'Wevicles Oliveira Batista Dos Santos', '', NOW(), NOW()),
(UUID(), 'Yago Santos Cruz', '', NOW(), NOW());
